temp change to debug ruby

diff --git a/.github/workflows/registry.yml b/.github/workflows/registry.yml
--- a/.github/workflows/registry.yml
+++ b/.github/workflows/registry.yml
@@ -21,90 +21,90 @@ jobs:
     
     steps:
     - uses: actions/checkout@v1
-    - name: test_docker_oci_helm
-      run: |
-        echo $JFROG_TOKEN | docker login $JFROG_ID.jfrog.io --username $JFROG_USERNAME --password-stdin
-        if docker pull ${{ secrets.JFROG_ID }}.jfrog.io/docker/ubuntu:latest; then
-          echo "Unexpected success: Image pulled successfully"
-          exit 1
-        else
-          echo "Expected failure: Received HTTP 400 error, test passed."
-          exit 0
-        fi
+    # - name: test_docker_oci_helm
+    #   run: |
+    #     echo $JFROG_TOKEN | docker login $JFROG_ID.jfrog.io --username $JFROG_USERNAME --password-stdin
+    #     if docker pull ${{ secrets.JFROG_ID }}.jfrog.io/docker/ubuntu:latest; then
+    #       echo "Unexpected success: Image pulled successfully"
+    #       exit 1
+    #     else
+    #       echo "Expected failure: Received HTTP 400 error, test passed."
+    #       exit 0
+    #     fi
 
-    - name: test_docker_oci_helm_dangerous
-      run: |
-        echo 'This is correct syntax, but its likely been taken down by the Docker team due to being malicious.'
-        echo $JFROG_TOKEN | docker login $JFROG_ID.jfrog.io --username $JFROG_USERNAME --password-stdin
-        if docker pull ${{ secrets.JFROG_ID }}.jfrog.io/docker/linux:3.11.0-12.19; then
-          echo "Unexpected success: Image pulled successfully"
-          exit 1
-        else
-          echo "Expected failure: Received manifest error, test passed."
-          exit 0
-        fi
+    # - name: test_docker_oci_helm_dangerous
+    #   run: |
+    #     echo 'This is correct syntax, but its likely been taken down by the Docker team due to being malicious.'
+    #     echo $JFROG_TOKEN | docker login $JFROG_ID.jfrog.io --username $JFROG_USERNAME --password-stdin
+    #     if docker pull ${{ secrets.JFROG_ID }}.jfrog.io/docker/linux:3.11.0-12.19; then
+    #       echo "Unexpected success: Image pulled successfully"
+    #       exit 1
+    #     else
+    #       echo "Expected failure: Received manifest error, test passed."
+    #       exit 0
+    #     fi
 
-    - name: test_npm
-      run: |
-        # Writes the auth token directly to .npmrc
-        echo "//${{ secrets.JFROG_ID }}.jfrog.io/artifactory/api/npm/npm/:_authToken=${{ secrets.JFROG_TOKEN }}" >> ~/.npmrc
+    # - name: test_npm
+    #   run: |
+    #     # Writes the auth token directly to .npmrc
+    #     echo "//${{ secrets.JFROG_ID }}.jfrog.io/artifactory/api/npm/npm/:_authToken=${{ secrets.JFROG_TOKEN }}" >> ~/.npmrc
 
-        # Sets the JFrog registry as the default
-        npm config set registry https://${{ secrets.JFROG_ID }}.jfrog.io/artifactory/api/npm/npm/
+    #     # Sets the JFrog registry as the default
+    #     npm config set registry https://${{ secrets.JFROG_ID }}.jfrog.io/artifactory/api/npm/npm/
 
-        # Installs the package
-        if npm install riot; then
-          echo "Unexpected success: Package installed successfully"
-          exit 1
-        else
-          echo "Expected failure: Package blocked, test passed."
-          exit 0
-        fi
+    #     # Installs the package
+    #     if npm install riot; then
+    #       echo "Unexpected success: Package installed successfully"
+    #       exit 1
+    #     else
+    #       echo "Expected failure: Package blocked, test passed."
+    #       exit 0
+    #     fi
 
-        # Resets the registry to the default NPM registry
-        npm config set registry https://registry.npmjs.org/
+    #     # Resets the registry to the default NPM registry
+    #     npm config set registry https://registry.npmjs.org/
 
-        # Removes the token from .npmrc after the script
-        sed -i '' "/${{ secrets.JFROG_ID }}.jfrog.io/d" ~/.npmrc
+    #     # Removes the token from .npmrc after the script
+    #     sed -i '' "/${{ secrets.JFROG_ID }}.jfrog.io/d" ~/.npmrc
 
-    - name: test_npm_dangerous
-      run: |
-        # Writes the auth token directly to .npmrc
-        echo "//${{ secrets.JFROG_ID }}.jfrog.io/artifactory/api/npm/npm/:_authToken=${{ secrets.JFROG_TOKEN }}" >> ~/.npmrc
+    # - name: test_npm_dangerous
+    #   run: |
+    #     # Writes the auth token directly to .npmrc
+    #     echo "//${{ secrets.JFROG_ID }}.jfrog.io/artifactory/api/npm/npm/:_authToken=${{ secrets.JFROG_TOKEN }}" >> ~/.npmrc
 
-        # Sets the JFrog registry as the default
-        npm config set registry https://${{ secrets.JFROG_ID }}.jfrog.io/artifactory/api/npm/npm/
+    #     # Sets the JFrog registry as the default
+    #     npm config set registry https://${{ secrets.JFROG_ID }}.jfrog.io/artifactory/api/npm/npm/
 
-        # Installs the package
-        if npm install mathlive@0.103.0; then
-          echo "Unexpected success: Package installed successfully"
-          exit 1
-        else
-          echo "Expected failure: Package blocked, test passed."
-          exit 0
-        fi
+    #     # Installs the package
+    #     if npm install mathlive@0.103.0; then
+    #       echo "Unexpected success: Package installed successfully"
+    #       exit 1
+    #     else
+    #       echo "Expected failure: Package blocked, test passed."
+    #       exit 0
+    #     fi
 
-        # Resets the registry to the default NPM registry
-        npm config set registry https://registry.npmjs.org/
+    #     # Resets the registry to the default NPM registry
+    #     npm config set registry https://registry.npmjs.org/
 
-        # Removes the token from .npmrc after the script
-        sed -i '' "/${{ secrets.JFROG_ID }}.jfrog.io/d" ~/.npmrc
+    #     # Removes the token from .npmrc after the script
+    #     sed -i '' "/${{ secrets.JFROG_ID }}.jfrog.io/d" ~/.npmrc
 
-    - name: test_go
-      run: |
-        echo "cd ../tests/go/; go clean -modcache; go mod tidy; export GOPROXY=https://:$JFROG_TOKEN@$JFROG_ID.jfrog.io/artifactory/api/go/go-virtual; go get github.com/gin-gonic/gin@v1.10.0",
+    # - name: test_go
+    #   run: |
+    #     echo "cd ../tests/go/; go clean -modcache; go mod tidy; export GOPROXY=https://:$JFROG_TOKEN@$JFROG_ID.jfrog.io/artifactory/api/go/go-virtual; go get github.com/gin-gonic/gin@v1.10.0",
     
-    - name: test_go_dangerous
-      run: |
-        echo "cd ../tests/go/; go clean -modcache; go mod tidy; export GOPROXY=https://:$JFROG_TOKEN@$JFROG_ID.jfrog.io/artifactory/api/go/go-virtual; go get github.com/golang/glog@v1.0.0"
+    # - name: test_go_dangerous
+    #   run: |
+    #     echo "cd ../tests/go/; go clean -modcache; go mod tidy; export GOPROXY=https://:$JFROG_TOKEN@$JFROG_ID.jfrog.io/artifactory/api/go/go-virtual; go get github.com/golang/glog@v1.0.0"
 
-    - name: test_python
-      run: |
-        echo "cd ../tests/python; chmod +x setup.sh; ./setup.sh"
+    # - name: test_python
+    #   run: |
+    #     echo "cd ../tests/python; chmod +x setup.sh; ./setup.sh"
 
-    - name: test_python_dangerous
-      run: |
-        echo "cd ../tests/python; chmod +x setup-dangerous.sh; ./setup-dangerous.sh"
+    # - name: test_python_dangerous
+    #   run: |
+    #     echo "cd ../tests/python; chmod +x setup-dangerous.sh; ./setup-dangerous.sh"
 
     - name: test_ruby
       run: |
