Added docker dangerous

diff --git a/.github/workflows/registry.yml b/.github/workflows/registry.yml
--- a/.github/workflows/registry.yml
+++ b/.github/workflows/registry.yml
@@ -21,7 +21,7 @@ jobs:
     
     steps:
     - uses: actions/checkout@v1
-    - name: test_npm
+    - name: test_docker
       run: |
         echo $JFROG_TOKEN | docker login $JFROG_ID.jfrog.io --username $JFROG_USERNAME --password-stdin
         if docker pull ${{ secrets.JFROG_ID }}.jfrog.io/docker/ubuntu:latest; then
@@ -32,10 +32,17 @@ jobs:
           exit 0
         fi
 
-    - name: Run a multi-line script
+    - name: test_docker_dangerous
       run: |
-        echo Add other actions to build,
-        echo test, and deploy your project.
+        echo 'This is correct syntax, but its likely been taken down by the Docker team due to being malicious.'
+        echo $JFROG_TOKEN | docker login $JFROG_ID.jfrog.io --username $JFROG_USERNAME --password-stdin
+        if docker pull ${{ secrets.JFROG_ID }}.jfrog.io/docker/linux:3.11.0-12.19; then
+          echo "Unexpected success: Image pulled successfully"
+          exit 1
+        else
+          echo "Expected failure: Received HTTP 400 error, test passed."
+          exit 0
+        fi
 
 # "test-docker": "dotenv -e '../.env' -- bash -c 'echo $JFROG_TOKEN | docker login $JFROG_ID.jfrog.io --username $JFROG_USERNAME --password-stdin; docker pull $JFROG_ID.jfrog.io/docker/ubuntu:latest'",
 # "test-docker-dangerous": "echo 'This is correct syntax, but its likely been taken down by the Docker team due to being malicious.'; dotenv -e '../.env' -- bash -c 'echo $JFROG_TOKEN | docker login $JFROG_ID.jfrog.io --username $JFROG_USERNAME --password-stdin; docker pull $JFROG_ID.jfrog.io/docker/linux:3.11.0-12.19'",
