Retake

diff --git a/.github/workflows/registry.yml b/.github/workflows/registry.yml
--- a/.github/workflows/registry.yml
+++ b/.github/workflows/registry.yml
@@ -24,7 +24,13 @@ jobs:
     - name: test_npm
       run: |
         echo $JFROG_TOKEN | docker login $JFROG_ID.jfrog.io --username $JFROG_USERNAME --password-stdin
-        docker pull $JFROG_ID.jfrog.io/docker/ubuntu:latest
+        if docker pull ${{ secrets.JFROG_ID }}.jfrog.io/docker/ubuntu:latest; then
+          echo "Unexpected success: Image pulled successfully"
+          exit 1
+        else
+          echo "Expected failure: Received HTTP 400 error, test passed."
+          exit 0
+        fi
 
     - name: Run a multi-line script
       run: |
